### ISSUE TITLE
Add your awesome open source projects

### ISSUE THREAD

**Issue by trevor-atlas** [trevoristall/awesomesource#1]
I'll happily accept your pull requests with great open-source projects. Go for it!

**Comment by suvojit-0x55aa** [comment]
Any suggestion on Titles(as in list Header) for adding Raspberry PI and Arduino Projects ??

**Comment by trevor-atlas** [comment]
@shin-migami Perhaps "Internet of things"? I guess it depends on what the library is for

**Comment by kaustubhhiware** [comment]
Hi @trevoristall !
Could we add other curated lists of specific resources , say a curated list for python resources ?
I am asking this because these lists are quite long and would make this list cumbersome .
A snappy version is ,if you are interested in particular language , go to this source, hence making this the source of all awesome sources (Mother of awesome ! :sunglasses: )

**Comment by trevor-atlas** [comment]
@kaustubhhiware That's a great idea, I'll make a PR for that this week 👍

**Comment by kaustubhhiware** [comment]
I was wondering if I could add some such lists myself in a PR ?

**Comment by trevor-atlas** [comment]
@kaustubhhiware Go for it!

**Comment by kaustubhhiware** [comment]
I have made , err _drastic_ changes to the way readme looks . 
Suggestions and edits are welcome !
Discuss here : #29
